version: "2"

services:
  debug:
    build: .
    command: node server.js
    volumes:
      - ./:/server
    ports:
      - "8083:80"
      - "9222:9222"
    environment:
      - NODE_ENV=development
      - NEWRELIC_LICENSE_KEY
  web:
    build: .
    command: node server.js
    ports:
      - "8083:80"
    environment:
      - NEWRELIC_LICENSE_KEY
