version: "2"

services:
  web:
    build: .
    command: npm start
    ports:
      - "8083:80"
    environment:
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_APP_NAME=newrelicbug
      - NEW_RELIC_NO_CONFIG_FILE=1
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LOG_LEVEL=info